### ISSUE TITLE
devDependencies support

### ISSUE THREAD

**Issue by cyberbiont** [alxlchnr/transitive-peerdeps#1]
Doing great,  but it seems to scan only "dependencies", not "devDependencies".
Whereas one of the common use cases could be devDependencies, that specify peerDependencies, such as ESlint shared configs (eslint-config-...).

**Comment by alxlchnr** [comment]
Hi @cyberbiont ,

thanks for your feature idea. I will add an additional command line flag `--dev` which will then scan devDependencies and will install missing peerDependencies to the devDependencies section.

**Comment by cyberbiont** [comment]
Thanks, this will help greatly in dealing with ESlint configurations!
